----------------------- 移动插件 --------------------------------------
return {
  "ggandor/leap.nvim",
  config = function()
    local leap = require "leap"
    -- leap.init_highlight(true)
    leap.setup {
      max_phase_one_targets = nil,
      highlight_unlabeled_phase_one_targets = false,
      max_highlighted_traversal_targets = 10,
      case_sensitive = false,
      equivalence_classes = { " \t\r\n" },
      substitute_chars = {},
      safe_labels = {},
      labels = {
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
      },
      special_keys = {
        repeat_search = "<enter>",
        next_phase_one_target = "<enter>",
        next_target = { "<enter>", ";" },
        prev_target = { "<tab>", "," },
        next_group = "<space>",
        prev_group = "<tab>",
        multi_accept = "<enter>",
        multi_revert = "<backspace>",
      },
    }
  end,
  event = "User AstroFile",
}
