return {
  "catppuccin/nvim",
  name = "catppuccin",
  opts = {
    transparent_background = vim.g.transparent_background,
    integration_default = false,
    integrations = {
      aerial = true,
      cmp = true,
      dap = true,
      dap_ui = true,
      gitsigns = true,
      indent_blankline = { enabled = true },
      markdown = true,
      mason = true,
      mini = true,
      native_lsp = { enabled = true, inlay_hints = { background = false } },
      neogit = true,
      neotree = true,
      noice = true,
      notify = true,
      overseer = true,
      rainbow_delimiters = true,
      semantic_tokens = true,
      symbols_outline = true,
      telescope = { enabled = true, style = "nvchad" },
      treesitter = true,
      ufo = true,
      which_key = true,
    },
    custom_highlights = {
      -- disable italics  for treesitter highlights
      TabLineFill = { link = "StatusLine" },
      LspInlayHint = { style = { "italic" } },
      UfoFoldedEllipsis = { link = "UfoFoldedFg" },
      ["@parameter"] = { style = {} },
      ["@type.builtin"] = { style = {} },
      ["@namespace"] = { style = {} },
      ["@text.uri"] = { style = { "underline" } },
      ["@tag.attribute"] = { style = {} },
      ["@tag.attribute.tsx"] = { style = {} },
    },
  },
}
